{
 "title": "ClickHouse logs dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(), LogAttributes['http.status_code'] AS status FROM r0.logs GROUP BY status"
    }
   ]
  },
  {
   "title": "Protocol pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(), LogAttributes['http.protocol'] AS protocol FROM r0.logs GROUP BY protocol"
    }
   ]
  },
  {
   "title": "Method Pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(), LogAttributes['http.method'] AS method FROM r0.logs GROUP BY method"
    }
   ]
  },
  {
   "title": "user-identifier Bar",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT count(), LogAttributes['http.user_agent'] AS user_agent FROM r0.logs GROUP BY user_agent"
    }
   ]
  },
  {
   "title": "Bytes transfered",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT LogAttributes['http.bytes'] AS bytes, count() FROM r0.logs GROUP BY bytes ORDER BY bytes DESC"
    }
   ]
  },
  {
   "title": "Logs in table format",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT  * \nFROM  r0.logs \nLIMIT 100"
    }
   ]
  },
  {
   "title": "Logs in Bar",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "rawSql": "SELECT * FROM r0.logs LIMIT 10" }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "rawSql": "SELECT * FROM r0.logs" }
   ]
  }
 ]
}