#
# Index config file for receiving logs in OpenTelemetry format.
# Link: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md
#

version: 0.4

index_id: logs

doc_mapping:
  field_mappings:
    - name: id
      type: u64
      fast: true
      stored: false
    - name: event_time
      type: datetime
      input_formats:
        - unix_timestamp
      fast: true
      stored: false
    - name: body
      type: text
      stored: false
      record: position
  timestamp_field: event_time

search_settings:
  default_search_fields: [body]
