[sources.logs]
type = "demo_logs"
format = "json"
decoding.codec = "json"

[transforms.modified_logs]
type = "remap"
inputs = ["logs"]
source = '''
  .id = to_int(now())
  .event_time = to_unix_timestamp(now())
  .body = "Some mock body"
'''

[sinks.clickhouse]
inputs = ["modified_logs"]
type = "clickhouse"
database = "r0"
endpoint = "http://clickhouse:8123"
table = "logs"
compression = "gzip"
tls.verify_hostname = false
auth.user = "demouser"
auth.password = "239QV8JkGmF9AZM"
auth.strategy = "basic"
batch.timeout_secs = 10
request.concurrency = "adaptive"

[sinks.quickwit]
type = "http"
inputs = ["modified_logs"]
encoding.codec = "json"
framing.method = "newline_delimited"
uri = "http://quickwit:7280/api/v1/logs/ingest"
